---
    version: '3'
    
    services:
      
      build_app:
        build: 
          dockerfile: ~/projects/devops-course/lesson_3,5,6/docker-projects/simple-java-maven-app/Dockerfile
      
      publish_app:
        image: my_app:v2