---
    version: '3'
    services:
      
      build_app:
        build: 
          context: .
      
      publish_app:
        image: lesson_7_build_app
        command: ["java", "-jar", "/root/projects/simple-java-maven-app/target/my-app-1.0-SNAPSHOT.jar"]