---
    version: '3'
    services:
      
      build_app:
        build: 
          context: .
          args:
            name: app:v3
      
      publish_app:
        image: name
        command: ["java", "-jar", "my-app-1.0-SNAPSHOT.jar"]