---
    version: '3'
    
    services:

      build_app:
        build: ~/projects/devops-course/lesson_3,5,6/docker-projects/simple-java-maven-app/
      
      publish_app:
        image: my_app:v2