---
    version: '3'
    
    services:

      build_app:
        build: 
          context: ~/projects/devops-course/lesson_3,5,6/docker-projects/simple-java-maven-app/
      
      publish_app:
        image: lesson_7_build_app